apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-pv
  namespace: dev
  labels:
    app: mysql-nfs-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
   server: 172.16.16.102
   path: /mnt/nfs_share
