apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs1-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.16.102
    path: /mnt/nfs_share

